# Generated by Django 4.2.7 on 2023-12-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_clients_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='observation',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
